#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_41
#define AUDIO_I2S_GPIO_WS GPIO_NUM_40
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_42
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_45
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_39

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_NC
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_2
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  0x82

#define BUILTIN_LED_GPIO        GPIO_NUM_38
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_NC
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_47
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define DISPLAY_MOSI_PIN      GPIO_NUM_4
#define DISPLAY_CLK_PIN       GPIO_NUM_5
#define DISPLAY_DC_PIN        GPIO_NUM_7
#define DISPLAY_RST_PIN       GPIO_NUM_NC
#define DISPLAY_CS_PIN        GPIO_NUM_6

#define DISPLAY_WIDTH   320
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY true
#define DISPLAY_INVERT_COLOR    true //颜色反转
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_SPI_MODE 0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_8 //背光使能
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT true

#define AXP173_I2C_ADDR 0x34

/* Camera pins */
#define CAMERA_PIN_PWDN 11
#define CAMERA_PIN_RESET -1
#define CAMERA_PIN_XCLK 16
#define CAMERA_PIN_SIOD 1
#define CAMERA_PIN_SIOC 2

#define CAMERA_PIN_D7 14
#define CAMERA_PIN_D6 18
#define CAMERA_PIN_D5 17
#define CAMERA_PIN_D4 9
#define CAMERA_PIN_D3 10
#define CAMERA_PIN_D2 15
#define CAMERA_PIN_D1 12
#define CAMERA_PIN_D0 21
#define CAMERA_PIN_VSYNC 48
#define CAMERA_PIN_HREF 46
#define CAMERA_PIN_PCLK 13

#define XCLK_FREQ_HZ 24000000

#endif // _BOARD_CONFIG_H_
